function offlinePrefix(p: offlineplayer) :: text:
	set {_data} to (instance of the plugin "LuckPerms").getServer().getServicesManager().load(class "net.luckperms.api.LuckPerms").getUserManager().loadUser({_p}.getUniqueId()).get().getCachedData().getMetaData()
	return (hex({_data}.getPrefix()))

function offlineSuffix(p: offlineplayer) :: text:
	set {_data} to (instance of the plugin "LuckPerms").getServer().getServicesManager().load(class "net.luckperms.api.LuckPerms").getUserManager().loadUser({_p}.getUniqueId()).get().getCachedData().getMetaData()
	return (hex({_data}.getSuffix()))

function rainbow(input: string, wrapAmount: number = -1, lightness: number = 0.5, offset: number = 0) :: string:
    set {_delta} to 360 / ({_wrapAmount} if {_wrapAmount} > 0, else length of {_input})
    set {_lightnessModifier} to (({_lightness}*2)-1) * 255
    set {_angle} to 90 + ({_delta} * {_offset})
    loop length of {_input} times:
        set {_character} to character at loop-value in {_input}
        if {_character} or (character at (loop-value )-1 in {_input}) is "§":
            if "abcdefklmnor0123456789" contains {_character}:
                set {_format} to (join {_format} and "&%{_character}%") if {_character} is not "r", else ("")
            continue
        set {_output} to join {_output}, "<##%decimalToHexadecimal((0.5 * (sin({_angle}) + 1)) * 255 + {_lightnessModifier})%%decimalToHexadecimal((0.5 * (sin({_angle} + 120) + 1)) * 255 + {_lightnessModifier})%%decimalToHexadecimal((0.5 * (sin({_angle} + 240) + 1)) * 255 + {_lightnessModifier})%>", {_format} and {_character}
        remove {_delta} from {_angle}
    return formatted {_output}

function decimalToHexadecimal(number: number) :: string:
    return ("00" if {_number} <= 0, else ("FF")) if {_number} is not between 0 and 255
    return join (character at (mod((floor({_number} / 16)), 16) + 1) in "0123456789ABCDEF") and (character at ((mod({_number}, 16)) + 1) in "0123456789ABCDEF")


function unhex(string: string) :: string:
    return (raw {_string}).replaceAll("<#([a-fA-F0-9]{6})>", "&#$1")

function hex(text: text):: text:
	return colored {_text}.replaceAll("&#([a-fA-F0-9]{6})", "<#$1>")

on load:
	set {-colorFormat::&0} to raw "<#000000>"
	set {-colorFormat::&1} to raw "<#0000AA>"
	set {-colorFormat::&2} to raw "<#00AA00>"
	set {-colorFormat::&3} to raw "<#00AAAA>"
	set {-colorFormat::&4} to raw "<#AA0000>"
	set {-colorFormat::&5} to raw "<#AA00AA>"
	set {-colorFormat::&6} to raw "<#FFAA00>"
	set {-colorFormat::&7} to raw "<#AAAAAA>"
	set {-colorFormat::&8} to raw "<#555555>"
	set {-colorFormat::&9} to raw "<#5555FF>"
	set {-colorFormat::&a} to raw "<#55FF55>"
	set {-colorFormat::&b} to raw "<#55FFFF>"
	set {-colorFormat::&c} to raw "<#FF5555>"
	set {-colorFormat::&d} to raw "<#FF55FF>"
	set {-colorFormat::&e} to raw "<#FFFF55>"
	set {-colorFormat::&f} to raw "<#FFFFFF>"
	set {-colorFormat::&l} to raw "<bold>"
	set {-colorFormat::&m} to raw "<strikethrough>"
	set {-colorFormat::&n} to raw "<underlined>"
	set {-colorFormat::&o} to raw "<italic>"
	set {-colorFormat::&r} to raw "<reset>"

function chatColorFormats(f: string) :: string:
	loop {-colorFormat::*}:
		replace all raw loop-index with raw loop-value in {_f}
	return {_f}

function chatFormatsOther(f: string) :: string:
	replace all "☠️" with "☠" in {_f}
	replace all ":fire:" with "🔥" in {_f}
	replace all ":snowman:" with "☃" in {_f}
	replace all ":cloud:" with "☁" in {_f}
	replace all ":checkmark:" with "✔" in {_f}
	replace all ":airplane:" with "✈" in {_f}
	replace all ":rook:" with "♜" in {_f}
	replace all "kys" with "kiss" in {_f}
	replace all "[item]" with "‱" in {_f}
	replace all "[i]" with "‱" in {_f}
	replace all "[hand]" with "‱" in {_f}
	replace all ":skull:" with "☠" in {_f}
	replace all "💀" with "☠" in {_f}
	replace all "<3" with "❤" in {_f}
	replace all ":ooo:" with "~.~" in {_f}
	replace all ":smile:" with "｡◕‿◕｡" in {_f}
	replace all ":angry:" with ">:(" in {_f}
	return {_f}


function getChatColor(p: offlineplayer, f: text):: strings:
	{chatcolor::%uuid of {_p}%} is "rank":
		set {_prefix} to raw prefix of {_p}
		if suffix of {_p} is not "":
			set {_prefix} to raw suffix of {_p}
			replace all " " in {_prefix} with ""
		set {_first} to (substring of (first 8 characters of raw {_prefix}) from characters 2 to 9)
		set {_last} to last 8 characters of raw {_prefix}
		replace all ("<", ">", "&") in {_first} and {_last} with ""
		return {_last} and {_first}
	{chatcolor::%uuid of {_p}%} is "rainbow":
		return getRainbowColors(uncolored formatted {_f})
	return "#%{chatcolor::%uuid of {_p}%}%" and "#%{chatcolor::%uuid of {_p}%}%"

function getRainbowColors(f: text) :: strings:
    set {_f} to raw rainbow({_f}, -1, 0.7, 5)
    replace all "&" in {_f} with ""
    set {_f} to formatted {_f}
    set {_last} to (first element of ((raw last color of {_f}) split at ">"))
    set {_f} to chatColorFormats({_f})
    set {_first} to first 9 characters of raw {_f}
    replace all ("#", "<", and ">") in ({_first} and {_last}) with ""
    return "#%{_last}%" and "#%{_first}%"

on async chat:
	cancel event
	set {chatcolor::%uuid of player%} to "ffffff" if {chatcolor::%uuid of player%} is not set
	set {_f} to raw hex(async chat message)
	set {_f} to chatColorFormats({_f}) if player is op
	set {_f} to chatFormatsOther({_f})
	set {_f} to uncolored formatted {_f} if player is not op
	set {_colors::*} to getChatColor(player, {_f})
	loop all players:
		play sound "minecraft:entity.experience_orb.pickup" with volume 0.5 with pitch 1 to loop-player if "%{_f}%" contains "%loop-player%"
		replace all raw "%loop-value%" with raw "<yellow>@%loop-player%</yellow>" in {_f}
	replace all raw "<reset>" in {_f} with raw "<reset><gradient:%{_colors::1}%:%{_colors::2}%>"
	set {_f} to mini message from "<gradient:%{_colors::1}%:%{_colors::2}%>%{_f}%"
	"%{_f}%" contains "‱":
		set {_t} to text component from "<white>%name of player's tool ? translate component of player's tool%"
		set hover event of {_t} to hover event showing player's tool
		component replace "‱" with (merge components ("&8[&r", {_t}, "&8]&r")) in {_f}
	set {_f} to merge components (hex(player's prefix), ((join (last color of (hex(prefix of player))) and (player's name))), ((hex(player's suffix)) ? ""), "&8:&r ", {_f})
	broadcast component {_f}

command chatcolor [<string>]:
	trigger:
		set {chatcolor::%uuid of player%} to arg ? {chatcolor::%uuid of player%}
		send {chatcolor::%uuid of player%}

on tab complete of "chatcolor":
	set tab completions for position 1 to "rank" and "rainbow"